test:
    name: tumhash-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 1
    rounds:
      - label: send review function - 30 requests
        description: add complaints benchmark with 30 requests
        txDuration: 100
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/sendReviewMessage.js,
            arguments: {contractId: tum-hash, subjects: 10,  maxKeys: 10},
          }
      - label: send review function - 60 requests
        description: add complaints benchmark with 30 requests
        txDuration: 100
        rateControl: { type: fixed-rate, opts: { tps: 60 } }
        workload:
          {
            module: /caliper-workload/sendReviewMessage.js,
            arguments: {contractId: tum-hash, subjects: 10,  maxKeys: 10},
          }
      - label: send review function - 90 requests
        description: add complaints benchmark with 30 requests
        txDuration: 100
        rateControl: { type: fixed-rate, opts: { tps: 90 } }
        workload:
          {
            module: /caliper-workload/sendReviewMessage.js,
            arguments: {contractId: tum-hash, subjects: 10,  maxKeys: 10},
          }

