test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 3
    rounds:
      - label: 20 tps - verifying orders
        txDuration: 60
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/nothing.js,
            arguments: {contractId: basic , assets: 500, counter: 0},
          }
