test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 3
    rounds:
      - label: 50 - adding drugs
        txDuration: 10
        rateControl: { type: fixed-rate, opts: { tps: 40 } }
        workload:
          {
            module: /caliper-workload/populateLedger.js,
            arguments: {contractId: basic , assets: 500, counter: 0},
          }
      - label: 30 - creating orders
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/populateLedgerWithTwo.js,
            arguments: {contractId: basic , assets: 500, counter: 0},
          }
      - label: 30 - verifying orders
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/verifyOrderWithTwo.js,
            arguments: {contractId: basic , assets: 500, counter: 0},
          }
