test:
    name: basic-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 4
    rounds:
      - label: check order / Pattern 1 - 30 requests
        description: check order benchmark with 30 requests
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/verifyOrderDetailsHashP11.js,
            arguments: {contractId: basic,assets: 1000, counter: 0},
          }

      - label: check order / Pattern 1 - 100 requests
        description: check order benchmark with 100 requests
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 100 } }
        workload:
          {
            module: /caliper-workload/verifyOrderDetailsHashP11.js,
            arguments: {contractId: basic,assets: 3100, counter: 0},
          }

      - label: check order / Pattern 1 - 200 requests
        description: check order benchmark with 200 requests
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 200 } }
        workload:
          {
            module: /caliper-workload/verifyOrderDetailsHashP11.js,
            arguments: {contractId: basic,assets: 6100, counter: 0},
          }                                                                                                 

      - label: check order / Pattern 1 - 300 requests
        description: check order benchmark with 300 requests
        txDuration: 30
        rateControl: { type: fixed-rate, opts: { tps: 300 } }
        workload:
          {
            module: /caliper-workload/verifyOrderDetailsHashP11.js,
            arguments: {contractId: basic,assets: 9100, counter: 0},
          }
