test:
    name: tumhash-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 5
    rounds:
      - label: add complaints function - 30 requests
        description: add complaints function  benchmark with 30 requests
        txDuration: 100
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/addComplaints.js,
            arguments: {contractId: tum-hash, subjects: 10,  maxKeys: 10},
          }
