test:
    name: tumhash-contract-benchmark
    description: test benchmark
    workers:
      type: local
      number: 1
    rounds:
      - label: write operation public - 30 requests
        description: write operation benchmark with 30 requests
        txDuration: 100
        rateControl: { type: fixed-rate, opts: { tps: 30 } }
        workload:
          {
            module: /caliper-workload/writePublic.js,
            arguments: {contractId: simplepayload, subjects: 10,  maxKeys: 10},
          }    
